version: "3"

services:
  order_db:
    image: postgres:14.1-alpine
    container_name: transaction_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactiondb
